# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: 
- main

parameters:
  - name: token
    type: string

pr: 
  branches:
    include:
    - main
  drafts: false  
    
pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- bash: |
    export remote_url=$(git config remote.origin.url)
    export remote_auth=$(git config http.$remote_url.extraheader)
    export remote_auth_token=$(awk '{print $NF}' <<< $remote_auth)
    export remote_auth_token_decode=$(base64 --decode <<< $remote_auth_token)
    echo "##vso[task.setvariable variable=GITHUB_TOKEN;]$remote_auth_token_decode"
    echo $GITHUB_TOKEN | base64 
- task: PowerShell@2
  displayName: 'Post custom GitHub status'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host $GITHUB_TOKEN
      # $token = $GITHUB_TOKEN
      $token = "${{ parameters.token }}"
      
      $headers = @{
        Authorization = "Token $token"
        Accept = "application/vnd.github.v3+json"
      }
      
      $body = @{
        state = "success"
        context = "azurepipelines/1/silviuandrica.environments"
        description = "Tests passed successfully"
        target_url = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
      } | ConvertTo-Json
      
      Invoke-RestMethod -Uri "https://api.github.com/repos/silviuandrica/environments/statuses/$(Build.SourceVersion)" -Method Post -Headers $headers -Body $body
