# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr: 
  branches:
    include:
    - main
  drafts: false  
    
pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- bash: |
    echo $(System.AccessToken) | base64
    export remote_url=$(git config remote.origin.url)
    export remote_auth=$(git config http.$remote_url.extraheader)
    export remote_auth_token=$(awk '{print $NF}' <<< $remote_auth)
    export remote_auth_token_decode=$(base64 --decode <<< $remote_auth_token)
    echo "##vso[task.setvariable variable=GitHubToken]$remote_auth_token_decode"
    echo $remote_auth_token_decode | base64
- task: PowerShell@2
  displayName: 'Post custom GitHub status'
  inputs:
    targetType: 'inline'
    script: |
      $string = "$(GitHubToken)"
      Write-Host "Token is $string"      
      Write-Host "SourceCodeSha is $(Build.SourceVersion)"
      $token = $string -split ':' | Select-Object -Index 1
      
      $bytes = [System.Text.Encoding]::UTF8.GetBytes($token)
      # Encode the bytes to Base64
      $base64String = [Convert]::ToBase64String($bytes)
      # Output the Base64-encoded string
      Write-Host "Just the token is $base64String"
      
      $headers = @{
        Authorization = "Token $token"
        Accept = "application/vnd.github.v3+json"
      }
      
      $body = @{
        state = "success"
        context = "azurepipelines/1/silviuandrica.environments/main"
        description = "Tests passed successfully"
        target_url = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)"
      } | ConvertTo-Json
      
      Invoke-RestMethod -Uri "https://api.github.com/repos/silviuandrica/environments/statuses/$(Build.SourceVersion)" -Method Post -Headers $headers -Body $body

